name: Add changeset to Renovate updates

on:
  pull_request_target:
    types: [opened, synchronize, labeled]
    paths:
      - '.github/workflows/sync_renovate-changesets.yml'
      - '**/yarn.lock'
      - '**/pnpm-lock.yaml'

jobs:
  renovate:
    name: Update Renovate PR
    runs-on: ${{ matrix.os }}
    if: contains(github.event.pull_request.labels.*.name, 'dependencies')

    strategy:
      matrix:
        os: [ubuntu-latest]


    steps:
      - name: Update PR
        uses: mscharley/dependency-changesets-action@v1.0.11
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          use-conventional-commits: true
          author-name: Renovate Changesets
          author-email: github+renovate@scharley.me